# Generated by Django 3.0.7 on 2020-06-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
