# Generated by Django 3.0.7 on 2020-06-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deviceType',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_id',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
